JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
value.h File Reference
#include "forwards.h"
#include <string>
#include <vector>
#include <exception>
#include <map>
Classes
class Json::Exception
Base class for all exceptions we throw.
class Json::RuntimeError
Exceptions which the user cannot easily avoid.
class Json::LogicError
Exceptions thrown by JSON_ASSERT/JSON_FAIL macros.
class Json::StaticString
Lightweight wrapper to tag static string.
class Json::Value
Represents a JSON value.
class Json::PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Json::Path
Experimental and untested: represents a "path" to access a node.
class Json::ValueIteratorBase
base class for Value iterators.
class Json::ValueConstIterator
const iterator for object and array value.
class Json::ValueIterator
Iterator for object and array value.
Namespaces
Json
JSON (JavaScript Object Notation).
Macros
#define JSONCPP_NORETURN __declspec(noreturn)
Enumerations
enum Json::ValueType {
Json::nullValue = 0, Json::intValue, Json::uintValue, Json::realValue,
Json::stringValue, Json::booleanValue, Json::arrayValue, Json::objectValue
}
used internally
enum Json::CommentPlacement { Json::commentBefore = 0, Json::commentAfterOnSameLine, Json::commentAfter, Json::numberOfCommentPlacement }
Functions
template<>
void std::swap (Json::Value &a, Json::Value &b)
Specialize std::swap() for Json::Value.
Macro Definition Documentation
#define JSONCPP_NORETURN __declspec(noreturn)
Definition at line 30 of file value.h.
Referenced by Json::__declspec().
Function Documentation
template<> void std::swap (Json::Value & a, Json::Value & b) inline
Specialize std::swap() for Json::Value.
Definition at line 859 of file value.h.
References Json::Value::swap(), and std::swap().
Referenced by std::swap().